const nodemailer = require("nodemailer");
const Mailgen = require("mailgen");

// Nodemailer Transport
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST, // e.g., "smtp.gmail.com"
  port: process.env.SMTP_PORT, // 465 (SSL) or 587 (TLS)
  secure: process.env.SMTP_SECURE === "false", // convert string to boolean
  auth: {
    user: process.env.SMTP_USER, // your email
    pass: process.env.SMTP_PASS, // your app password
  },
});

// Mailgen Setup
const mailGenerator = new Mailgen({
  theme: "default",
  product: {
    name: "Software Engineering - FUTO",
    link: "https://futo.edu.ng/department/soe",
    logo: "https://futo.edu.ng/logo.png",
  },
});

export const sendEmailToMultiple = async ({ emails, notice }) => {
  try {
    // Email body generated by Mailgen
    const emailBody = {
      body: {
        name: "Dear Student",
        intro:
          "We’ve got a new notice for you released by Software Engineering Departmment.",
        table: {
          data: [
            { Title: notice.title },
            { Date: new Date(notice.createdAt).toDateString() },
            { "Ref Id": notice.refId },
            { Description: notice.description },
          ],
        },
        action: {
          instructions: "Click the button below to view the notice:",
          button: {
            color: "#272362",
            text: "View Notice",
            link: `hhttp://localhost:8000/api/notice/:${notice._id}`,
          },
        },
        outro:
          "For any questions, reach us at contact@futo.edu.ng_department_soe",
      },
    };

    const emailTemplate = mailGenerator.generate(emailBody);

    const message = {
      from: `"Software Engineering - FUTO" <${config.smtp.user}>`,
      to: emails, // array of emails
      subject:
        "New Notice Released on Software Engineering Department Notice Board",
      html: emailTemplate,
    };

    const info = await transporter.sendMail(message);
    console.log("Emails sent successfully:", info.messageId);
    return info;
  } catch (error) {
    console.error("Error sending email:", error);
    throw error;
  }
};
